const fs = require('fs');
const file = 'src/data/speakerPublicationData.ts';
let data = fs.readFileSync(file, 'utf8');

const leaders = `  },
  {
    id: 'skr-rel-adeboye',
    speakerName: 'PASTOR E. A. ADEBOYE',
    organisation: 'The Redeemed Christian Church of God (RCCG)',
    position: 'General Overseer',
    photographUrl: '',
    logoUrl: '',
    approvedTopic: 'Opening Prayer / Interfaith Safety Prayer',
    session: 'National Traditional & Religious Leadership Safety Colloquium',
    transcript: '',
    editedTranscript: '',
    handbookTitle: '',
    approvalStatus: {
      photo: false,
      bio: false,
      topic: false,
      transcript: false,
      handbook: false,
      podcast: false,
      cover: false,
      publication: false
    },
    publicationDate: '2026-11-17',
    pageCount: 0,
    softCopyPrice: 0,
    hardCopyPrice: 0,
    podcastEpisodeNumber: 0,
    podcastDescription: '',
    showNotes: [],
    keyTakeaways: [],
    category: 'FAITH_LEADERSHIP',
    specialRole: 'Opening Prayer',
    publicVisibility: 'PUBLIC'
  },
  {
    id: 'skr-rel-sultan',
    speakerName: 'H.E. ALHAJI (DR.) SA’AD ABUBAKAR III, CFR',
    organisation: 'Nigeria Supreme Council for Islamic Affairs (NSCIA)',
    position: 'Sultan of Sokoto',
    photographUrl: '',
    logoUrl: '',
    approvedTopic: 'Interfaith Safety Prayer',
    session: 'National Traditional & Religious Leadership Safety Colloquium',
    transcript: '',
    editedTranscript: '',
    handbookTitle: '',
    approvalStatus: {
      photo: false,
      bio: false,
      topic: false,
      transcript: false,
      handbook: false,
      podcast: false,
      cover: false,
      publication: false
    },
    publicationDate: '2026-11-17',
    pageCount: 0,
    softCopyPrice: 0,
    hardCopyPrice: 0,
    podcastEpisodeNumber: 0,
    podcastDescription: '',
    showNotes: [],
    keyTakeaways: [],
    category: 'FAITH_LEADERSHIP',
    specialRole: 'Interfaith Safety Prayer',
    publicVisibility: 'PUBLIC'
  },
  {
    id: 'skr-rel-olukoya',
    speakerName: 'DR. D. K. OLUKOYA',
    organisation: 'Mountain of Fire and Miracles Ministries (MFM)',
    position: 'General Overseer',
    photographUrl: '',
    logoUrl: '',
    approvedTopic: 'Interfaith Safety Prayer',
    session: 'National Traditional & Religious Leadership Safety Colloquium',
    transcript: '',
    editedTranscript: '',
    handbookTitle: '',
    approvalStatus: {
      photo: false,
      bio: false,
      topic: false,
      transcript: false,
      handbook: false,
      podcast: false,
      cover: false,
      publication: false
    },
    publicationDate: '2026-11-17',
    pageCount: 0,
    softCopyPrice: 0,
    hardCopyPrice: 0,
    podcastEpisodeNumber: 0,
    podcastDescription: '',
    showNotes: [],
    keyTakeaways: [],
    category: 'FAITH_LEADERSHIP',
    specialRole: 'Interfaith Safety Prayer',
    publicVisibility: 'PUBLIC'
  },
  {
    id: 'skr-rel-oyedepo',
    speakerName: 'BISHOP DAVID OYEDEPO',
    organisation: 'Living Faith Church Worldwide',
    position: 'Presiding Bishop',
    photographUrl: '',
    logoUrl: '',
    approvedTopic: 'Interfaith Safety Prayer',
    session: 'National Traditional & Religious Leadership Safety Colloquium',
    transcript: '',
    editedTranscript: '',
    handbookTitle: '',
    approvalStatus: {
      photo: false,
      bio: false,
      topic: false,
      transcript: false,
      handbook: false,
      podcast: false,
      cover: false,
      publication: false
    },
    publicationDate: '2026-11-17',
    pageCount: 0,
    softCopyPrice: 0,
    hardCopyPrice: 0,
    podcastEpisodeNumber: 0,
    podcastDescription: '',
    showNotes: [],
    keyTakeaways: [],
    category: 'FAITH_LEADERSHIP',
    specialRole: 'Interfaith Safety Prayer',
    publicVisibility: 'PUBLIC'
  }
];`;

data = data.replace(/  \}\n\];/, leaders);
fs.writeFileSync(file, data);
console.log('done');
